image:
  registry: docker.io
  name: mifril/binance-challenge
  tag: latest
  pullPolicy: Always

args:
  - "--action"
  - "prometheus"
  - "--only-trading"

replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: metrics
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: metrics
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
startupProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: metrics
    scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
