apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: binance-exporter
          image: "{{ $.Values.image.registry }}/{{ $.Values.image.name}}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: metrics
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe: {{ toYaml .Values.startupProbe | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
