apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
